version: "2"

checks:
  method-complexity:
    enabled: true
    config:
      threshold: 8

plugins:
  eslint:
    enabled: true
    channel: eslint-5

exclude_patterns:
  - "config/"
  - "cov-int/"
  - "coverage/"
  - "docs/"
  - "scripts/"
  - "**/node_modules/"
  - "**/spec/"
  - "**/test/"
  - "**/.jsbits/"
  - "**/*.d.ts"
